version: '3.8'

services:
  cmsadmin:
    image: mlabfactory/php8-apache:v1.3
    container_name: budgetcontrol-cmsadmin
    networks:
      - budgetcontrol_network
    restart: unless-stopped
    volumes:
      - .:/var/www/workdir

networks:
  budgetcontrol_network:
    external: true
    name: budgetcontrol_network